version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5044:5432"
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: local
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    command: redis-server -requirepass local
    ports:
      - "6388:6379"

